[[JSON_C]]
arch = "aarch64"
git-tree-sha1 = "4396d1840d656e932365c8e5b3b4fb90d390633d"
os = "macos"

    [[JSON_C.download]]
    sha256 = "6c9045d44c60e3ac5661052ae59176976ed83c507ede039d24212e4a80889c2d"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.aarch64-apple-darwin.tar.gz"
[[JSON_C]]
arch = "aarch64"
git-tree-sha1 = "b08063774b49a05de90051ce2cbb48ac5ec0b50a"
libc = "glibc"
os = "linux"

    [[JSON_C.download]]
    sha256 = "a1bb51f821e116c398ed03c8c733e2feec05d86c031740237543c2d2e86df06b"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.aarch64-linux-gnu.tar.gz"
[[JSON_C]]
arch = "aarch64"
git-tree-sha1 = "b212552f743afbfe26259047c0b2eab4ef96e3a4"
libc = "musl"
os = "linux"

    [[JSON_C.download]]
    sha256 = "69ec26659d2ab1a74258e7166491e49b91108a95dc72b8aeec86cd26e768c312"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.aarch64-linux-musl.tar.gz"
[[JSON_C]]
arch = "aarch64"
git-tree-sha1 = "3a26c02fe358d5a42646d6fc7c498ab93d7f7d25"
os = "freebsd"

    [[JSON_C.download]]
    sha256 = "ec06253814a8e185bc349a00846c037306bbc499849e96a7d6c0947fd67bbd5a"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.aarch64-unknown-freebsd.tar.gz"
[[JSON_C]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dc07a01b0e772d87866777c6b8fb6d538c573add"
libc = "glibc"
os = "linux"

    [[JSON_C.download]]
    sha256 = "360cccad1b2dbc6c72904f9ac8ee949711b6e551db14834438d7c812187a7131"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.armv6l-linux-gnueabihf.tar.gz"
[[JSON_C]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0b957bca25efa6f23e54bf95040dade4c31c1773"
libc = "musl"
os = "linux"

    [[JSON_C.download]]
    sha256 = "d1018b11b96c0447264b400b70210ed4a5f985899b1d9c4a146224b7ffde87ae"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.armv6l-linux-musleabihf.tar.gz"
[[JSON_C]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b6a24ddf7df50a79095b89d2f1dcab86963da4a8"
libc = "glibc"
os = "linux"

    [[JSON_C.download]]
    sha256 = "6da78e35148f904007744e35f5998ddb79105a5d837337c24639107e72b2cf74"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.armv7l-linux-gnueabihf.tar.gz"
[[JSON_C]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bd78088d4e040a721e2a155e328745173dbe68a7"
libc = "musl"
os = "linux"

    [[JSON_C.download]]
    sha256 = "0c982bbd5de91cdb73b2669b30e53d1288285667bcd2d0ce282e91481e73d639"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.armv7l-linux-musleabihf.tar.gz"
[[JSON_C]]
arch = "i686"
git-tree-sha1 = "3dca8541263554168ffaa8bf2580aa1397f68f7c"
libc = "glibc"
os = "linux"

    [[JSON_C.download]]
    sha256 = "3a5683c5ace5030851eee3ae676c766641bc833e0c9fbfbba79068608dd373fb"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.i686-linux-gnu.tar.gz"
[[JSON_C]]
arch = "i686"
git-tree-sha1 = "9393168c0b6440b1145d009b116ac6f278d32658"
libc = "musl"
os = "linux"

    [[JSON_C.download]]
    sha256 = "2f5104ad27ab491992af8baa9727d77bc5b9ab20235c334ced82cd97246bbc9c"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.i686-linux-musl.tar.gz"
[[JSON_C]]
arch = "i686"
git-tree-sha1 = "458bb73c70a25ff2ca9534dbbfc3965abc028c0e"
os = "windows"

    [[JSON_C.download]]
    sha256 = "8933276448a7b8a77bd906b91392f36bbba7a311fea6b6961804affeb573a02e"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.i686-w64-mingw32.tar.gz"
[[JSON_C]]
arch = "powerpc64le"
git-tree-sha1 = "0bb2cdd0bc634416c73dad5925183f4bbba5226b"
libc = "glibc"
os = "linux"

    [[JSON_C.download]]
    sha256 = "b3caf4b39bdb94efd54101ef18726c64277010b7446b4fe08751e3d132db3916"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.powerpc64le-linux-gnu.tar.gz"
[[JSON_C]]
arch = "riscv64"
git-tree-sha1 = "2bb8ec8c40a40a2be809f223545d01d57698ced2"
libc = "glibc"
os = "linux"

    [[JSON_C.download]]
    sha256 = "77e83dc37af1d9795f1440ac40add1d52219fae79a69bebaa4ef628e6d018add"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.riscv64-linux-gnu.tar.gz"
[[JSON_C]]
arch = "x86_64"
git-tree-sha1 = "2bcb6909a94458b043b0058e39f2e9d66c57c581"
os = "macos"

    [[JSON_C.download]]
    sha256 = "60348ff702a52b1a5c09c8ef2d77876b33c9c03b1da381a2589d5305ffcdbbe8"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.x86_64-apple-darwin.tar.gz"
[[JSON_C]]
arch = "x86_64"
git-tree-sha1 = "4ef78c183385a4cb9633bf9462b1188f239b6604"
libc = "glibc"
os = "linux"

    [[JSON_C.download]]
    sha256 = "964043400239ee1e79c1dd38eafdaf2ad4185e7675c869764495921907502848"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.x86_64-linux-gnu.tar.gz"
[[JSON_C]]
arch = "x86_64"
git-tree-sha1 = "8276389181c606f2e57c4fcc5472e5db8f472569"
libc = "musl"
os = "linux"

    [[JSON_C.download]]
    sha256 = "fa32fa34fcefdf25df75f2d3a3cffdefc585b48e7d6344a1292abbac32e922d7"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.x86_64-linux-musl.tar.gz"
[[JSON_C]]
arch = "x86_64"
git-tree-sha1 = "82c45538468185570d0eae99d45182514a195e26"
os = "freebsd"

    [[JSON_C.download]]
    sha256 = "5160f4c36070ceba8dd2f001835e44e329b06356de60cc37af173dfb454108cf"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.x86_64-unknown-freebsd.tar.gz"
[[JSON_C]]
arch = "x86_64"
git-tree-sha1 = "8f9d27a5ed63fddf8e4209a3908fa9871329eea6"
os = "windows"

    [[JSON_C.download]]
    sha256 = "e34abee149b12d6c460961f7ffa47c6e0b643c7102ff0d7330ed827e0c6f2df0"
    url = "https://github.com/JuliaBinaryWrappers/JSON_C_jll.jl/releases/download/JSON_C-v0.18.0+0/JSON_C.v0.18.0.x86_64-w64-mingw32.tar.gz"
